# site settings
title: Charisse
subtitle: Foo
email: charisseishere@gmail.com
description: Charisse is an architectural <br /> designer and illustrator
url: # the base hostname & protocol for your site
author: Charisse Foo
street_address:
city:
state:
zip_code:
country: Singapore
phone:

# homepage tiles
tiles-source: posts # accepts "posts" or "pages"
tiles-count: 10

# social settings
500px_url:
facebook_url: https://www.facebook.com/charissefoo
github_url: https://github.com/charissefoo/
# artstation_url: https://www.artstation.com/charissefoo
behance_url: https://www.behance.net/charissefoo
instagram_url: https://instagram.com/charissefoo
linkedin_url: https://www.linkedin.com/in/charissefoo
pinterest_url:
slack_url:
twitter_url:

# build settings
markdown: kramdown

sass:
  style: compressed
